### ISSUE TITLE
Error with requirements file.

### ISSUE THREAD

**Issue by mrx7014** [dragonked2/Egyscan#13]
This error happend when install requirements file 
`pip install -r requirements.txt`

Error: pip install -r requirements.txt
Collecting logging
  Downloading logging-0.4.9.6.tar.gz (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.0/96.0 kB 2.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 8, in <module>
          import _distutils_hack.override  # noqa: F401
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/_distutils_hack/override.py", line 1, in <module>
          __import__('_distutils_hack').do_override()
        File "/usr/lib/python3/dist-packages/_distutils_hack/__init__.py", line 77, in do_override
          ensure_local_distutils()
        File "/usr/lib/python3/dist-packages/_distutils_hack/__init__.py", line 63, in ensure_local_distutils
          core = importlib.import_module('distutils.core')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 22, in <module>
          from .dist import Distribution
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 12, in <module>
          import logging
        File "/tmp/pip-install-m23ylqv5/logging_d7225d883f274ec38a8f6aa1fc3ed180/logging/__init__.py", line 618
          raise NotImplementedError, 'emit must be implemented '\
                                   ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I think this error because **setup.py**  file not included in tool directory,And you put too files for tool egy.py & egyscan.py,this tool need some improvement.

**Comment by dragonked2** [comment]
Thank You For Your Kind interest into improving Egyscan 
First of all Lets Try To Fix this issue 
have you tried 
pip install logging
?
if yes and still no progress i suggest you start downloading the logging library manually and install it on your machine 
https://pypi.org/project/logging/

Steps 
download
extract contents into folder 
open cmd or terminal what ever os you are using then 
run 
python setup.py install 
then 
restart the application 
python egyscan.py
python3 egyscan.py 
depending on your os system 

And Keep me updated via email : ali@dmgexpert.com
