### ISSUE TITLE
Error installing project dependencies

### ISSUE THREAD

**Issue by plusiv** [dragonked2/Egyscan#14]
An error with the package `logging` occurs when installing the project dependencies.

```shell
root@abb3a1c513e0:/Egyscan# pip install -r requirements.txt
Collecting logging
  Downloading logging-0.4.9.6.tar.gz (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.0/96.0 KB 1.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/usr/lib/python3/dist-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 77, in <module>
          __import__('pkg_resources.extern.packaging.specifiers')
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/specifiers.py", line 24, in <module>
          from .utils import canonicalize_version
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/utils.py", line 8, in <module>
          from .tags import Tag, parse_tag
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/tags.py", line 5, in <module>
          import logging
        File "/tmp/pip-install-g5v88z1v/logging_64aa7193546a4653aa69d837c01460a5/logging/__init__.py", line 618
          raise NotImplementedError, 'emit must be implemented '\
                                   ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by dragonked2** [comment]
Hello and Thanks For The Feedback however the problem is not with Egyscan itself 
but a library used in it Called "logging" 
some systems cant install it automaticlly because of updates 
so i suggest to install it manually from here
https://pypi.org/project/logging/

Download the Package 
Extract it
python setup.py install
Rerun Egyscan 
Good luck :)
