### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by dariomlopez** [dragonked2/Egyscan#26]
When I try to do pip install -r requirements.txt I have this error and I can't put Egyscan to work:
Defaulting to user installation because normal site-packages is not writeable
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/holehe-1.61-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330                                          
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/zoomeye-2.2.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330                                        
Collecting logging (from -r requirements.txt (line 2))                           
  Using cached logging-0.4.9.6.tar.gz (96 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/home/dario/.local/lib/python3.11/site-packages/setuptools/__init__.py", line 7, in <module>
          import _distutils_hack.override  # noqa: F401
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/dario/.local/lib/python3.11/site-packages/_distutils_hack/override.py", line 1, in <module>
          __import__('_distutils_hack').do_override()
        File "/home/dario/.local/lib/python3.11/site-packages/_distutils_hack/__init__.py", line 77, in do_override
          ensure_local_distutils()
        File "/home/dario/.local/lib/python3.11/site-packages/_distutils_hack/__init__.py", line 63, in ensure_local_distutils
          core = importlib.import_module('distutils.core')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/dario/.local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 22, in <module>
          from .dist import Distribution
        File "/home/dario/.local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 12, in <module>
          import logging
        File "/tmp/pip-install-ewo9t077/logging_e96f27c6c6144857bc0530dd7c0c1174/logging/__init__.py", line 618
          raise NotImplementedError, 'emit must be implemented '\
                                   ^
      SyntaxError: invalid syntax
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by dragonked2** [comment]
download logging library manually via pypip website 
and install it via 
python setup.py install
after extracting the zip file content
